language: java
jdk: oraclejdk8
after_success:
- ".buildscript/deploy_to_maven.sh"
env:
  global:
  - secure: cadS2RXzt+whdZk04koNiuAWH88z7MRIBqTxuIRvsyn9hGd0k3zWI97wdNAP+jewBRov9an5sOyUAIEQfuybuh41atBUrlvC54eT4DfAEtMj/8T5sP4+GsW6ybMoxSa+t6bFWkvIz+VJjVUYSqlwqF+MjAJnYYGGUKCXjCS9EEs=
  - secure: LmSb0lkvLHeytOda/UCosJZ0TCwcdkkiXp7i8jLz8/BCS6/d3daNTfm4DvFpEHWh0D+NeLjBqp6Y+GXVOfGixyRyrO2H1OJgDFfjZOE7WNXWBEu121u+3c7dic0G5jBUOJNibLnzmmP8EqKvsfael799nfK2RR8qdLLEF3zF7Xc=
notifications:
  email: false
cache:
  directories:
  - "$HOME/.m2"

before_install:
# made with "travis encrypt-file codesigning.asc -r SpoonLabs/gumtree-spoon-ast-diff --add"
- openssl aes-256-cbc -K $encrypted_9809c3ea697e_key -iv $encrypted_9809c3ea697e_iv
  -in .buildscript/codesigning.asc.enc -out codesigning.asc -d
- gpg --fast-import codesigning.asc
